# fly.toml app configuration file generated for dev-opnform-ui on 2025-09-03T14:27:38+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dev-opnform-ui'
primary_region = 'syd'

[build]
  dockerfile = 'docker/Dockerfile.client'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
