# syntax=docker/dockerfile

---
services:
  api: &api
    image: jhumanj/opnform-api:latest
    container_name: opnform-api
    environment: &api-environment  # Add this anchor
      DB_HOST: db
      REDIS_HOST: redis
      DB_DATABASE: ${DB_DATABASE:-forge}
      DB_USERNAME: ${DB_USERNAME:-forge}
      DB_PASSWORD: ${DB_PASSWORD:-forge}
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      FILESYSTEM_DISK: local
      LOCAL_FILESYSTEM_VISIBILITY: public
    env_file:
    - .env.api
    volumes:
    - opnform_storage:/usr/share/nginx/html/storage:rw

  api-worker:
    image: jhumanj/opnform-api:latest
    container_name: opnform-api-worker
    command: php artisan queue:work
    environment:
      <<: *api-environment
      IS_API_WORKER: "true"
    env_file:
    - .env.api
    volumes:
    - opnform_storage:/usr/share/nginx/html/storage:rw

  ui:
    image: jhumanj/opnform-client:latest
    container_name: opnform-ui
    env_file:
    - .env.client

  redis:
    image: redis:7
    container_name: opnform-redis

  db:
    image: postgres:16
    container_name: opnform-db
    environment:
      POSTGRES_DB: ${DB_DATABASE:-forge}
      POSTGRES_USER: ${DB_USERNAME:-forge}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-forge}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ingress:
    image: jhumanj/opnform-web:latest
    container_name: opnform-web
    env_file:
    - .env.web
    ports:
      - 8222:80

volumes:
  postgres-data:
  opnform_storage:
